monolog:
  handlers:
    file_log:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug

    syslog_handler:
      type: syslog
      path: "%kernel.logs_dir%/cron_exception.log"
      level: error