parameters:
    notifier.guzzle.timeout: 15
    notifier.guzzle.exchange_rates.tries_amount: 2
    notifier.exchange_rates.load_rates_gap: 120
    notifier.proxy.load.amount: 36
    runtime.lock_dir: '%kernel.project_dir%/var/lock'
    app.notification.min_gap: 3600
    app.notification.to_email: 'thetangro@ttprojectx.ru'
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\ExchangeRates\Providers\CredoMainPageAdapters\AdapterInterface:
        class: App\ExchangeRates\Providers\CredoMainPageAdapters\GuzzleAdapter
    logger:
        alias: 'monolog.logger'
        public: true
    App\ExchangeRates\Checkers\Pool:
        class: App\ExchangeRates\Checkers\Pool
        autowire: true
        arguments:
            $checkers:
                - '@App\ExchangeRates\Checkers\EuroHigherUSDChecker'
    App\Notifications\Notifiers\TelegramNotifier:
        class: \App\Notifications\Notifiers\TelegramNotifier
        autowire: true
        arguments:
            $botToken: '%env(NOTIFIER_TELEGRAM_BOT_TOKEN)%'
            $chatId: '%env(NOTIFIER_TELEGRAM_CHAT_ID)%'